[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install fastapi uvicorn databases[postgresql] sqlalchemy asyncpg passlib[bcrypt] python-jose[cryptography]"]

[start]
command = "python server.py"
